# pyright: reportAttributeAccessIssue=false, reportUndefinedVariable=false
"""add name field to player model

Revision ID: 5e0fa657cbf0
Revises: 9a3c473fc37e
Create Date: 2025-12-02 15:47:15.063154

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e0fa657cbf0"
down_revision: str | None = "9a3c473fc37e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "name")
    # ### end Alembic commands ###
