# pyright: reportAttributeAccessIssue=false, reportUndefinedVariable=false
"""add ranking system fields

Revision ID: 83a7da4e5496
Revises: 9cb8c3fca24d
Create Date: 2025-12-04 15:06:05.460569

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83a7da4e5496"
down_revision: str | None = "9cb8c3fca24d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("FRIENDLY", "RANKED", "DUEL", name="pvpmode").create(op.get_bind())
    op.add_column(
        "pvp_challenges",
        sa.Column(
            "mode",
            postgresql.ENUM("FRIENDLY", "RANKED", "DUEL", name="pvpmode", create_type=False),
            nullable=False,
        ),
    )
    op.add_column(
        "pvp_ranks", sa.Column("score_updated_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.add_column("pvp_ranks", sa.Column("daily_plays", sa.Integer(), nullable=False))
    op.add_column(
        "pvp_ranks", sa.Column("last_play_date", sa.DateTime(timezone=True), nullable=True)
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="eventtype",
        new_values=[
            "EARN_MONEY",
            "SPEND_MONEY",
            "OBTAIN_CARD",
            "GACHA_PULL",
            "ADMIN_INCREASE_CURRENCY",
            "ADMIN_DECREASE_CURRENCY",
            "ADMIN_SET_CURRENCY",
            "TRADE_CREATED",
            "TRADE_ACCEPTED",
            "TRADE_REJECTED",
            "TRADE_CANCELLED",
            "TRADE_CARD_SENT",
            "TRADE_CARD_RECEIVED",
            "TRADE_MONEY_SENT",
            "TRADE_MONEY_RECEIVED",
            "RANKED_SCORE_GAINED",
            "RANKED_SCORE_LOST",
            "RANKED_WEEKLY_REWARD",
            "RANKED_PLAY_FEE",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="event_logs", column_name="event_type")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="eventtype",
        new_values=[
            "EARN_MONEY",
            "SPEND_MONEY",
            "OBTAIN_CARD",
            "GACHA_PULL",
            "ADMIN_INCREASE_CURRENCY",
            "ADMIN_DECREASE_CURRENCY",
            "ADMIN_SET_CURRENCY",
            "TRADE_CREATED",
            "TRADE_ACCEPTED",
            "TRADE_REJECTED",
            "TRADE_CANCELLED",
            "TRADE_CARD_SENT",
            "TRADE_CARD_RECEIVED",
            "TRADE_MONEY_SENT",
            "TRADE_MONEY_RECEIVED",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="event_logs", column_name="event_type")
        ],
        enum_values_to_rename=[],
    )
    op.drop_column("pvp_ranks", "last_play_date")
    op.drop_column("pvp_ranks", "daily_plays")
    op.drop_column("pvp_ranks", "score_updated_at")
    op.drop_column("pvp_challenges", "mode")
    sa.Enum("FRIENDLY", "RANKED", "DUEL", name="pvpmode").drop(op.get_bind())
    # ### end Alembic commands ###
