# pyright: reportAttributeAccessIssue=false, reportUndefinedVariable=false
"""add admin currency event types

Revision ID: 9a3c473fc37e
Revises: 4a9ebec07b2d
Create Date: 2025-12-01 09:29:10.451073

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "9a3c473fc37e"
down_revision: str | None = "4a9ebec07b2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="eventtype",
        new_values=[
            "EARN_MONEY",
            "SPEND_MONEY",
            "OBTAIN_CARD",
            "ADMIN_INCREASE_CURRENCY",
            "ADMIN_DECREASE_CURRENCY",
            "ADMIN_SET_CURRENCY",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="event_logs", column_name="event_type")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="eventtype",
        new_values=["EARN_MONEY", "SPEND_MONEY", "OBTAIN_CARD"],
        affected_columns=[
            TableReference(table_schema="public", table_name="event_logs", column_name="event_type")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
