# pyright: reportAttributeAccessIssue=false, reportUndefinedVariable=false
"""add gacha pity and pull logging system

Revision ID: 32593fe8498e
Revises: 5e0fa657cbf0
Create Date: 2025-12-02 17:01:23.317402

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32593fe8498e"
down_revision: str | None = "5e0fa657cbf0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gacha_pity",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("pool_id", sa.Integer(), nullable=False),
        sa.Column("pity_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"]),
        sa.ForeignKeyConstraint(["pool_id"], ["card_pools.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gacha_pity_id"), "gacha_pity", ["id"], unique=False)
    op.create_index(op.f("ix_gacha_pity_player_id"), "gacha_pity", ["player_id"], unique=False)
    op.create_index(op.f("ix_gacha_pity_pool_id"), "gacha_pity", ["pool_id"], unique=False)
    op.create_table(
        "gacha_pulls",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("pool_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("was_pity", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"]),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"]),
        sa.ForeignKeyConstraint(["pool_id"], ["card_pools.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gacha_pulls_card_id"), "gacha_pulls", ["card_id"], unique=False)
    op.create_index(op.f("ix_gacha_pulls_id"), "gacha_pulls", ["id"], unique=False)
    op.create_index(op.f("ix_gacha_pulls_player_id"), "gacha_pulls", ["player_id"], unique=False)
    op.create_index(op.f("ix_gacha_pulls_pool_id"), "gacha_pulls", ["pool_id"], unique=False)
    op.sync_enum_values(
        enum_schema="public",
        enum_name="eventtype",
        new_values=[
            "EARN_MONEY",
            "SPEND_MONEY",
            "OBTAIN_CARD",
            "GACHA_PULL",
            "ADMIN_INCREASE_CURRENCY",
            "ADMIN_DECREASE_CURRENCY",
            "ADMIN_SET_CURRENCY",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="event_logs", column_name="event_type")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="eventtype",
        new_values=[
            "EARN_MONEY",
            "SPEND_MONEY",
            "OBTAIN_CARD",
            "ADMIN_INCREASE_CURRENCY",
            "ADMIN_DECREASE_CURRENCY",
            "ADMIN_SET_CURRENCY",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="event_logs", column_name="event_type")
        ],
        enum_values_to_rename=[],
    )
    op.drop_index(op.f("ix_gacha_pulls_pool_id"), table_name="gacha_pulls")
    op.drop_index(op.f("ix_gacha_pulls_player_id"), table_name="gacha_pulls")
    op.drop_index(op.f("ix_gacha_pulls_id"), table_name="gacha_pulls")
    op.drop_index(op.f("ix_gacha_pulls_card_id"), table_name="gacha_pulls")
    op.drop_table("gacha_pulls")
    op.drop_index(op.f("ix_gacha_pity_pool_id"), table_name="gacha_pity")
    op.drop_index(op.f("ix_gacha_pity_player_id"), table_name="gacha_pity")
    op.drop_index(op.f("ix_gacha_pity_id"), table_name="gacha_pity")
    op.drop_table("gacha_pity")
    # ### end Alembic commands ###
