# pyright: reportAttributeAccessIssue=false, reportUndefinedVariable=false
"""add trade event types

Revision ID: 9cb8c3fca24d
Revises: 32593fe8498e
Create Date: 2025-12-04 00:09:46.515657

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9cb8c3fca24d"
down_revision: str | None = "32593fe8498e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="eventtype",
        new_values=[
            "EARN_MONEY",
            "SPEND_MONEY",
            "OBTAIN_CARD",
            "GACHA_PULL",
            "ADMIN_INCREASE_CURRENCY",
            "ADMIN_DECREASE_CURRENCY",
            "ADMIN_SET_CURRENCY",
            "TRADE_CREATED",
            "TRADE_ACCEPTED",
            "TRADE_REJECTED",
            "TRADE_CANCELLED",
            "TRADE_CARD_SENT",
            "TRADE_CARD_RECEIVED",
            "TRADE_MONEY_SENT",
            "TRADE_MONEY_RECEIVED",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="event_logs", column_name="event_type")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="eventtype",
        new_values=[
            "EARN_MONEY",
            "SPEND_MONEY",
            "OBTAIN_CARD",
            "GACHA_PULL",
            "ADMIN_INCREASE_CURRENCY",
            "ADMIN_DECREASE_CURRENCY",
            "ADMIN_SET_CURRENCY",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="event_logs", column_name="event_type")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
