# pyright: reportAttributeAccessIssue=false, reportUndefinedVariable=false
"""add rate field to shop_items

Revision ID: b32969a684ab
Revises: 83a7da4e5496
Create Date: 2025-12-05 15:46:33.228362

"""

from collections.abc import Sequence

from alembic_postgresql_enum import TableReference
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b32969a684ab"
down_revision: str | None = "83a7da4e5496"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shop_items", sa.Column("rate", sa.Float(), nullable=True))
    op.execute("UPDATE shop_items SET rate = 1.0")
    op.alter_column("shop_items", "rate", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shop_items", "rate")
    # ### end Alembic commands ###
