# pyright: reportAttributeAccessIssue=false, reportUndefinedVariable=false
"""initial scheme

Revision ID: 96d4cba3197c
Revises:
Create Date: 2025-11-07 10:21:06.458654

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96d4cba3197c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_pools",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_card_pools_id"), "card_pools", ["id"], unique=False)
    op.create_index(op.f("ix_card_pools_name"), "card_pools", ["name"], unique=False)
    op.create_table(
        "cards",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("image", sa.LargeBinary(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "rarity",
            sa.Enum("C", "R", "SR", "SSR", "UR", "LR", "EX", name="rarity"),
            nullable=False,
        ),
        sa.Column("attack", sa.Integer(), nullable=True),
        sa.Column("defense", sa.Integer(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cards_id"), "cards", ["id"], unique=False)
    op.create_index(op.f("ix_cards_name"), "cards", ["name"], unique=False)
    op.create_table(
        "players",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_players_id"), "players", ["id"], unique=False)
    op.create_table(
        "card_pool_cards",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pool_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"]),
        sa.ForeignKeyConstraint(["pool_id"], ["card_pools.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_card_pool_cards_card_id"), "card_pool_cards", ["card_id"], unique=False
    )
    op.create_index(op.f("ix_card_pool_cards_id"), "card_pool_cards", ["id"], unique=False)
    op.create_index(
        op.f("ix_card_pool_cards_pool_id"), "card_pool_cards", ["pool_id"], unique=False
    )
    op.create_table(
        "deck_cards",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"]),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deck_cards_card_id"), "deck_cards", ["card_id"], unique=False)
    op.create_index(op.f("ix_deck_cards_id"), "deck_cards", ["id"], unique=False)
    op.create_index(op.f("ix_deck_cards_name"), "deck_cards", ["name"], unique=False)
    op.create_index(op.f("ix_deck_cards_player_id"), "deck_cards", ["player_id"], unique=False)
    op.create_table(
        "event_logs",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum("EARN_MONEY", "SPEND_MONEY", "OBTAIN_CARD", name="eventtype"),
            nullable=False,
        ),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_logs_id"), "event_logs", ["id"], unique=False)
    op.create_index(op.f("ix_event_logs_player_id"), "event_logs", ["player_id"], unique=False)
    op.create_table(
        "pvp_challenges",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("challenger_id", sa.Integer(), nullable=False),
        sa.Column("opponent_id", sa.Integer(), nullable=False),
        sa.Column("winner_id", sa.Integer(), nullable=True),
        sa.Column("bet", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ONGOING",
                "ACCEPTED",
                "REJECTED",
                "COMPLETED",
                "CANCELLED",
                name="pvpstatus",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["challenger_id"], ["players.id"]),
        sa.ForeignKeyConstraint(["opponent_id"], ["players.id"]),
        sa.ForeignKeyConstraint(["winner_id"], ["players.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pvp_challenges_challenger_id"), "pvp_challenges", ["challenger_id"], unique=False
    )
    op.create_index(op.f("ix_pvp_challenges_id"), "pvp_challenges", ["id"], unique=False)
    op.create_index(
        op.f("ix_pvp_challenges_opponent_id"), "pvp_challenges", ["opponent_id"], unique=False
    )
    op.create_index(
        op.f("ix_pvp_challenges_winner_id"), "pvp_challenges", ["winner_id"], unique=False
    )
    op.create_table(
        "pvp_ranks",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pvp_ranks_id"), "pvp_ranks", ["id"], unique=False)
    op.create_index(op.f("ix_pvp_ranks_player_id"), "pvp_ranks", ["player_id"], unique=False)
    op.create_index(op.f("ix_pvp_ranks_week"), "pvp_ranks", ["week"], unique=False)
    op.create_table(
        "shop_items",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("type", sa.Enum("CARD", "ITEM", name="shopitemtype"), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shop_items_card_id"), "shop_items", ["card_id"], unique=False)
    op.create_index(op.f("ix_shop_items_id"), "shop_items", ["id"], unique=False)
    op.create_index(op.f("ix_shop_items_name"), "shop_items", ["name"], unique=False)
    op.create_table(
        "trades",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proposer_id", sa.Integer(), nullable=False),
        sa.Column("receiver_id", sa.Integer(), nullable=False),
        sa.Column("offered_card_id", sa.Integer(), nullable=False),
        sa.Column("requested_card_id", sa.Integer(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "ACCEPTED", "REJECTED", "COMPLETED", "CANCELLED", name="tradestatus"
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(requested_card_id IS NOT NULL) OR (price IS NOT NULL)",
            name="requested_card_or_price_not_null",
        ),
        sa.ForeignKeyConstraint(["offered_card_id"], ["cards.id"]),
        sa.ForeignKeyConstraint(["proposer_id"], ["players.id"]),
        sa.ForeignKeyConstraint(["receiver_id"], ["players.id"]),
        sa.ForeignKeyConstraint(["requested_card_id"], ["cards.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trades_id"), "trades", ["id"], unique=False)
    op.create_index(op.f("ix_trades_offered_card_id"), "trades", ["offered_card_id"], unique=False)
    op.create_index(op.f("ix_trades_proposer_id"), "trades", ["proposer_id"], unique=False)
    op.create_index(op.f("ix_trades_receiver_id"), "trades", ["receiver_id"], unique=False)
    op.create_index(
        op.f("ix_trades_requested_card_id"), "trades", ["requested_card_id"], unique=False
    )
    op.create_table(
        "inventories",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["shop_items.id"]),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inventories_id"), "inventories", ["id"], unique=False)
    op.create_index(op.f("ix_inventories_item_id"), "inventories", ["item_id"], unique=False)
    op.create_index(op.f("ix_inventories_player_id"), "inventories", ["player_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventories_player_id"), table_name="inventories")
    op.drop_index(op.f("ix_inventories_item_id"), table_name="inventories")
    op.drop_index(op.f("ix_inventories_id"), table_name="inventories")
    op.drop_table("inventories")
    op.drop_index(op.f("ix_trades_requested_card_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_receiver_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_proposer_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_offered_card_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_id"), table_name="trades")
    op.drop_table("trades")
    op.drop_index(op.f("ix_shop_items_name"), table_name="shop_items")
    op.drop_index(op.f("ix_shop_items_id"), table_name="shop_items")
    op.drop_index(op.f("ix_shop_items_card_id"), table_name="shop_items")
    op.drop_table("shop_items")
    op.drop_index(op.f("ix_pvp_ranks_week"), table_name="pvp_ranks")
    op.drop_index(op.f("ix_pvp_ranks_player_id"), table_name="pvp_ranks")
    op.drop_index(op.f("ix_pvp_ranks_id"), table_name="pvp_ranks")
    op.drop_table("pvp_ranks")
    op.drop_index(op.f("ix_pvp_challenges_winner_id"), table_name="pvp_challenges")
    op.drop_index(op.f("ix_pvp_challenges_opponent_id"), table_name="pvp_challenges")
    op.drop_index(op.f("ix_pvp_challenges_id"), table_name="pvp_challenges")
    op.drop_index(op.f("ix_pvp_challenges_challenger_id"), table_name="pvp_challenges")
    op.drop_table("pvp_challenges")
    op.drop_index(op.f("ix_event_logs_player_id"), table_name="event_logs")
    op.drop_index(op.f("ix_event_logs_id"), table_name="event_logs")
    op.drop_table("event_logs")
    op.drop_index(op.f("ix_deck_cards_player_id"), table_name="deck_cards")
    op.drop_index(op.f("ix_deck_cards_name"), table_name="deck_cards")
    op.drop_index(op.f("ix_deck_cards_id"), table_name="deck_cards")
    op.drop_index(op.f("ix_deck_cards_card_id"), table_name="deck_cards")
    op.drop_table("deck_cards")
    op.drop_index(op.f("ix_card_pool_cards_pool_id"), table_name="card_pool_cards")
    op.drop_index(op.f("ix_card_pool_cards_id"), table_name="card_pool_cards")
    op.drop_index(op.f("ix_card_pool_cards_card_id"), table_name="card_pool_cards")
    op.drop_table("card_pool_cards")
    op.drop_index(op.f("ix_players_id"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_cards_name"), table_name="cards")
    op.drop_index(op.f("ix_cards_id"), table_name="cards")
    op.drop_table("cards")
    op.drop_index(op.f("ix_card_pools_name"), table_name="card_pools")
    op.drop_index(op.f("ix_card_pools_id"), table_name="card_pools")
    op.drop_table("card_pools")
    # ### end Alembic commands ###
