# pyright: reportAttributeAccessIssue=false, reportUndefinedVariable=false
"""add daily bet tracking to pvp_ranks

Revision ID: 5e6963bcc876
Revises: b32969a684ab
Create Date: 2025-12-05 17:36:18.187494

"""

from collections.abc import Sequence

from alembic_postgresql_enum import TableReference
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e6963bcc876"
down_revision: str | None = "b32969a684ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pvp_ranks", sa.Column("daily_bet_amount", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "pvp_ranks", sa.Column("last_bet_date", sa.DateTime(timezone=True), nullable=True)
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="eventtype",
        new_values=[
            "EARN_MONEY",
            "SPEND_MONEY",
            "OBTAIN_CARD",
            "SELL_CARD",
            "GACHA_PULL",
            "ADMIN_INCREASE_CURRENCY",
            "ADMIN_DECREASE_CURRENCY",
            "ADMIN_SET_CURRENCY",
            "TRADE_CREATED",
            "TRADE_ACCEPTED",
            "TRADE_REJECTED",
            "TRADE_CANCELLED",
            "TRADE_CARD_SENT",
            "TRADE_CARD_RECEIVED",
            "TRADE_MONEY_SENT",
            "TRADE_MONEY_RECEIVED",
            "RANKED_SCORE_GAINED",
            "RANKED_SCORE_LOST",
            "RANKED_WEEKLY_REWARD",
            "RANKED_PLAY_FEE",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="event_logs", column_name="event_type")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="eventtype",
        new_values=[
            "EARN_MONEY",
            "SPEND_MONEY",
            "OBTAIN_CARD",
            "GACHA_PULL",
            "ADMIN_INCREASE_CURRENCY",
            "ADMIN_DECREASE_CURRENCY",
            "ADMIN_SET_CURRENCY",
            "TRADE_CREATED",
            "TRADE_ACCEPTED",
            "TRADE_REJECTED",
            "TRADE_CANCELLED",
            "TRADE_CARD_SENT",
            "TRADE_CARD_RECEIVED",
            "TRADE_MONEY_SENT",
            "TRADE_MONEY_RECEIVED",
            "RANKED_SCORE_GAINED",
            "RANKED_SCORE_LOST",
            "RANKED_WEEKLY_REWARD",
            "RANKED_PLAY_FEE",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="event_logs", column_name="event_type")
        ],
        enum_values_to_rename=[],
    )
    op.drop_column("pvp_ranks", "last_bet_date")
    op.drop_column("pvp_ranks", "daily_bet_amount")
    # ### end Alembic commands ###
