# pyright: reportAttributeAccessIssue=false, reportUndefinedVariable=false
"""add card support to inventory

Revision ID: ea2b46a86102
Revises: c2426d74d07d
Create Date: 2025-11-23 22:42:38.001217

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea2b46a86102"
down_revision: str | None = "c2426d74d07d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inventories", sa.Column("card_id", sa.Integer(), nullable=True))
    op.alter_column("inventories", "item_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_index(op.f("ix_inventories_card_id"), "inventories", ["card_id"], unique=False)
    op.create_foreign_key(None, "inventories", "cards", ["card_id"], ["id"])
    op.create_check_constraint(
        "item_or_card_not_null", "inventories", "(item_id IS NOT NULL) OR (card_id IS NOT NULL)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("item_or_card_not_null", "inventories", type_="check")
    op.drop_constraint(None, "inventories", type_="foreignkey")
    op.drop_index(op.f("ix_inventories_card_id"), table_name="inventories")
    op.alter_column("inventories", "item_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("inventories", "card_id")
    # ### end Alembic commands ###
