# pyright: reportAttributeAccessIssue=false, reportUndefinedVariable=false
"""add currency field to player

Revision ID: 4a9ebec07b2d
Revises: 59851fe4b5ef
Create Date: 2025-11-30 22:23:46.345965

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a9ebec07b2d"
down_revision: str | None = "59851fe4b5ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deck_cards_name"), table_name="deck_cards")
    op.drop_column("deck_cards", "name")
    op.add_column(
        "players", sa.Column("currency", sa.Integer(), nullable=False, server_default="0")
    )
    # Remove server default after adding the column
    op.alter_column("players", "currency", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "currency")
    op.add_column(
        "deck_cards", sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False)
    )
    op.create_index(op.f("ix_deck_cards_name"), "deck_cards", ["name"], unique=False)
    # ### end Alembic commands ###
