from enum import StrEnum


class CardRarity(StrEnum):
    C = "C"
    R = "R"
    SR = "SR"
    SSR = "SSR"
    UR = "UR"
    LR = "LR"
    EX = "EX"


class ShopItemType(StrEnum):
    CARD = "CARD"
    ITEM = "ITEM"


class TradeStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class PvPMode(StrEnum):
    FRIENDLY = "FRIENDLY"
    RANKED = "RANKED"
    DUEL = "DUEL"


class PvPStatus(StrEnum):
    PENDING = "PENDING"
    ONGOING = "ONGOING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class EventType(StrEnum):
    EARN_MONEY = "EARN_MONEY"
    SPEND_MONEY = "SPEND_MONEY"
    OBTAIN_CARD = "OBTAIN_CARD"
    SELL_CARD = "SELL_CARD"
    GACHA_PULL = "GACHA_PULL"
    ADMIN_INCREASE_CURRENCY = "ADMIN_INCREASE_CURRENCY"
    ADMIN_DECREASE_CURRENCY = "ADMIN_DECREASE_CURRENCY"
    ADMIN_SET_CURRENCY = "ADMIN_SET_CURRENCY"
    TRADE_CREATED = "TRADE_CREATED"
    TRADE_ACCEPTED = "TRADE_ACCEPTED"
    TRADE_REJECTED = "TRADE_REJECTED"
    TRADE_CANCELLED = "TRADE_CANCELLED"
    TRADE_CARD_SENT = "TRADE_CARD_SENT"
    TRADE_CARD_RECEIVED = "TRADE_CARD_RECEIVED"
    TRADE_MONEY_SENT = "TRADE_MONEY_SENT"
    TRADE_MONEY_RECEIVED = "TRADE_MONEY_RECEIVED"
    RANKED_SCORE_GAINED = "RANKED_SCORE_GAINED"
    RANKED_SCORE_LOST = "RANKED_SCORE_LOST"
    RANKED_WEEKLY_REWARD = "RANKED_WEEKLY_REWARD"
    RANKED_PLAY_FEE = "RANKED_PLAY_FEE"


class CardSortField(StrEnum):
    ID = "id"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"


class SortOrder(StrEnum):
    ASC = "asc"
    DESC = "desc"
